from pathlib import Path
from html import escape
root=Path(__file__).parent
nav=[('index.html','Home'),('schedule.html','Schedule'),('passes.html','Passes'),('instructors.html','Instructors'),('about.html','About'),('contact.html','Contact')]
notice='<div class="draft-banner" role="status"><div class="wrap">Website preview · Class times, prices, team, location and contact details await Paila approval.</div></div>'
header='''<header class="site-header"><div class="wrap nav"><a class="brand" href="index.html" aria-label="Paila Pilates home"><span class="mark" aria-hidden="true">P</span><span>PAILA <b>PILATES</b><small>MOVE WITH INTENTION</small></span></a><button class="menu" type="button" aria-label="Open menu" aria-controls="navigation" aria-expanded="false">Menu</button><nav id="navigation" aria-label="Main navigation">{links}</nav></div></header>'''
footer='''<footer class="footer"><div class="wrap footer-grid"><div><strong>PAILA PILATES</strong><p>A preview of the Paila digital home. Business details are awaiting owner approval.</p></div><div><strong>Explore</strong><p><a href="schedule.html">Schedule</a> · <a href="passes.html">Passes</a> · <a href="instructors.html">Team</a></p></div><div><strong>Next step</strong><p><a href="contact.html">Contact details pending approval</a></p></div></div><div class="wrap fine">© <span id="year"></span> Paila Pilates · Draft, not a live booking service</div></footer>'''
def panel(kicker,title,body,href=None,label=None):
    link=f'<a class="button outline" href="{href}">{label}</a>' if href else ''
    return f'<article class="card"><p class="eyebrow">{kicker}</p><h3>{title}</h3><p>{body}</p>{link}</article>'
pages={
'index.html':('Home','A calm place to begin','''<section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">Paila Pilates · Website preview</p><h1>Find your way<br><em>to movement.</em></h1><p class="lead">A welcoming home for your Pilates journey. We are preparing the studio details, class information and ways to get in touch.</p><div class="actions"><a class="button" href="about.html">Discover Paila</a><a class="button outline" href="schedule.html">Class information</a></div></div><div class="hero-art" aria-hidden="true"><div class="sun"></div><div class="arch"></div><span>MOVE<br>WITH<br>INTENTION</span></div></div></section><section class="section"><div class="wrap"><p class="eyebrow">Explore</p><h2>Everything in its place.</h2><div class="grid three">'''+panel('01','Classes','See the schedule once dates, levels and locations are approved.','schedule.html','View schedule')+panel('02','Passes','Compare approved options when pricing and terms are ready.','passes.html','Explore passes')+panel('03','People','Meet the instructors when their profiles and photos are approved.','instructors.html','Meet the team')+'''</div></div></section><section class="section wash"><div class="wrap split"><div><p class="eyebrow">Thoughtful by design</p><h2>Room to move at your own pace.</h2></div><p class="lead">The Paila site will make it easy to learn about classes and choose a next step. Studio claims, facilities and policies will be added only from approved sources.</p></div></section>'''),
'schedule.html':('Schedule','Class schedule','''<section class="page-hero"><div class="wrap"><p class="eyebrow">Classes</p><h1>Make time to move.</h1><p class="lead">The Paila timetable has not been approved for publication.</p></div></section><section class="section"><div class="wrap grid two">'''+panel('Awaiting details','Schedule coming soon','Class names, dates, times, instructor assignments and locations will appear here after the owner confirms them.')+panel('Booking status','Reservations are not open','This draft does not accept bookings or save visitor information. A live booking service must be chosen and configured before reservations open.','contact.html','Contact information')+'''</div></section>'''),
'passes.html':('Passes','Passes and pricing','''<section class="page-hero"><div class="wrap"><p class="eyebrow">Ways to practise</p><h1>Choose your rhythm.</h1><p class="lead">Passes, prices and terms will be published after Paila approves them.</p></div></section><section class="section"><div class="wrap grid two">'''+panel('Prices pending','No offers are on sale','The reference site’s example prices and memberships have not been transferred to Paila.')+panel('Terms pending','Clear terms before purchase','Pass validity, cancellation, refunds, taxes and payment methods need owner approval. No payment collection is enabled.')+'''</div></section>'''),
'instructors.html':('Instructors','Meet the team','''<section class="page-hero"><div class="wrap"><p class="eyebrow">Your guides</p><h1>People make the practice.</h1><p class="lead">Approved instructor profiles and photos will be added here.</p></div></section><section class="section"><div class="wrap">'''+panel('Profiles pending','The Paila team','We will add each instructor’s approved name, experience, teaching approach and portrait after review.')+'''</div></section>'''),
'about.html':('About','About Paila Pilates','''<section class="page-hero"><div class="wrap"><p class="eyebrow">Our story</p><h1>Movement starts somewhere.</h1><p class="lead">This page is ready for Paila’s approved story, values and studio information.</p></div></section><section class="section"><div class="wrap grid two">'''+panel('Story pending','The studio story','Founding story, mission and practice approach will come from Paila-approved sources.')+panel('Visit information pending','The studio','The address, opening hours, accessibility details and first-visit guidance need confirmation.')+'''</div></section>'''),
'contact.html':('Contact','Contact Paila Pilates','''<section class="page-hero"><div class="wrap"><p class="eyebrow">Get in touch</p><h1>Let’s start a conversation.</h1><p class="lead">Official contact channels and studio location will be added after approval.</p></div></section><section class="section"><div class="wrap grid two">'''+panel('Contact pending','Official channels','Email, phone, WhatsApp and social links are intentionally absent until verified by the owner.')+panel('Location pending','Find the studio','The address and directions will appear when the location is confirmed.')+'''</div></section>'''),
'member.html':('Member area','Member services','''<section class="page-hero"><div class="wrap"><p class="eyebrow">Member services</p><h1>More is on its way.</h1><p class="lead">Secure member accounts are planned, but are not available in this website draft.</p></div></section><section class="section"><div class="wrap">'''+panel('Coming later','A secure member experience','A real booking or account service is needed before members can sign in, view bookings, make payments or store personal information. No demo PIN or browser-only account is offered here.')+'''</div></section>''')}
for name,(title,description,body) in pages.items():
    links=''.join(f'<a href="{href}"'+(' aria-current="page"' if href==name else '')+f'>{label}</a>' for href,label in nav)
    page='<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+escape(description,quote=True)+'"><meta name="robots" content="noindex,nofollow"><title>'+escape(title)+' | Paila Pilates</title><link rel="stylesheet" href="assets/css/styles.css"><script defer src="data/site-data.js"></script><script defer src="assets/js/shared.js"></script></head><body><a class="skip" href="#main">Skip to content</a>'+notice+header.replace('{links}',links)+'<main id="main">'+body+'</main>'+footer+'</body></html>\n'
    (root/name).write_text(page)
